import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Footer from "./components/Footer";
import Header from "./components/Header";
import "./globals.css";
import { TRPCProvider } from "./providers/trpcProvider";
import UserContextProvider from "./providers/UserProvider";

const inter = Inter({ subsets: ["latin"], variable: "--font-inter" });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={inter.className}>
      <head />
      <body suppressHydrationWarning={true} className="bg-gray-100">
        <UserContextProvider user={""} isAdmin={false}>
          <TRPCProvider>
            <Header />
            {children}
            <Footer />
          </TRPCProvider>
        </UserContextProvider>
      </body>
    </html>
  );
}
