import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Toaster } from "react-hot-toast";
import "./globals.css";
import Head from "./head";
import Header from "../components/Header";
import Footer from "../components/Footer";
import UserContextProvider from "../providers/UserProvider";
import { QueryClientContextProvider } from "../providers/trpcProvider";

const inter = Inter({ subsets: ["latin"], variable: "--font-inter" });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={inter.className}>
      <Head />
      <body suppressHydrationWarning={true} className="bg-gray-100">
        <UserContextProvider user={""} isAdmin={false}>
          <QueryClientContextProvider>
            <Header />
            {children}
            <Toaster position="top-center" />
            <Footer />
          </QueryClientContextProvider>
        </UserContextProvider>
      </body>
    </html>
  );
}
